"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.RESET_PASSWORD_COMPLETE = exports.LOGOUT_COMPLETE = exports.LOGOUT_START = exports.LOGIN_COMPLETE = exports.LOGIN_START = exports.REGISTER_COMPLETE = exports.REGISTER_START = exports.SET_TOKEN = exports.AUTH_STRATEGIES = exports.SOCKET_DISCONNECTED = exports.SOCKET_CONNECTED = exports.SOCKET_RECONNECT = exports.SOCKET_CONNECT = exports.INIT_STATE = void 0;
var INIT_STATE = 'auth/INIT_STATE';
exports.INIT_STATE = INIT_STATE;
var SOCKET_CONNECT = 'auth/SOCKET_CONNECT';
exports.SOCKET_CONNECT = SOCKET_CONNECT;
var SOCKET_RECONNECT = 'auth/SOCKET_RECONNECT';
exports.SOCKET_RECONNECT = SOCKET_RECONNECT;
var SOCKET_CONNECTED = 'auth/SOCKET_CONNECTED';
exports.SOCKET_CONNECTED = SOCKET_CONNECTED;
var SOCKET_DISCONNECTED = 'auth/SOCKET_DISCONNECTED';
exports.SOCKET_DISCONNECTED = SOCKET_DISCONNECTED;
var AUTH_STRATEGIES = 'auth/AUTH_STRATEGIES';
exports.AUTH_STRATEGIES = AUTH_STRATEGIES;
var SET_TOKEN = 'auth/SET_TOKEN';
exports.SET_TOKEN = SET_TOKEN;
var REGISTER_START = 'auth/REGISTER_START';
exports.REGISTER_START = REGISTER_START;
var REGISTER_COMPLETE = 'auth/REGISTER_COMPLETE';
exports.REGISTER_COMPLETE = REGISTER_COMPLETE;
var LOGIN_START = 'auth/LOGIN_START';
exports.LOGIN_START = LOGIN_START;
var LOGIN_COMPLETE = 'auth/LOGIN_COMPLETE';
exports.LOGIN_COMPLETE = LOGIN_COMPLETE;
var LOGOUT_START = 'auth/LOGOUT_START';
exports.LOGOUT_START = LOGOUT_START;
var LOGOUT_COMPLETE = 'auth/LOGOUT_COMPLETE';
exports.LOGOUT_COMPLETE = LOGOUT_COMPLETE;
var RESET_PASSWORD_COMPLETE = 'auth/RESET_PASSWORD_COMPLETE'; //# sourceMappingURL=auth.js.map

exports.RESET_PASSWORD_COMPLETE = RESET_PASSWORD_COMPLETE;
//# sourceMappingURL=auth.js.map
