"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.EXIT_FULLSCREEN = exports.ENTER_FULLSCREEN = exports.LOAD_HISTORY_COMPLETE = exports.LOAD_HISTORY_START = exports.BOOTH_SKIP = exports.ADVANCE = void 0;
var ADVANCE = 'booth/ADVANCE';
exports.ADVANCE = ADVANCE;
var BOOTH_SKIP = 'booth/SKIP';
exports.BOOTH_SKIP = BOOTH_SKIP;
var LOAD_HISTORY_START = 'booth/LOAD_HISTORY_START';
exports.LOAD_HISTORY_START = LOAD_HISTORY_START;
var LOAD_HISTORY_COMPLETE = 'booth/LOAD_HISTORY_COMPLETE';
exports.LOAD_HISTORY_COMPLETE = LOAD_HISTORY_COMPLETE;
var ENTER_FULLSCREEN = 'playback/ENTER_FULLSCREEN';
exports.ENTER_FULLSCREEN = ENTER_FULLSCREEN;
var EXIT_FULLSCREEN = 'playback/EXIT_FULLSCREEN';
exports.EXIT_FULLSCREEN = EXIT_FULLSCREEN;
//# sourceMappingURL=booth.js.map
