"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UNMUTE_USER = exports.MUTE_USER = exports.REMOVE_ALL_MESSAGES = exports.REMOVE_USER_MESSAGES = exports.REMOVE_MESSAGE = exports.LOG = exports.NOTIFY = exports.SEND_MESSAGE = exports.RECEIVE_MESSAGE = exports.SET_MOTD_COMPLETE = exports.SET_MOTD_START = exports.RECEIVE_MOTD = void 0;
var RECEIVE_MOTD = 'chat/RECEIVE_MOTD';
exports.RECEIVE_MOTD = RECEIVE_MOTD;
var SET_MOTD_START = 'chat/SET_MOTD_START';
exports.SET_MOTD_START = SET_MOTD_START;
var SET_MOTD_COMPLETE = 'chat/SET_MOTD_COMPLETE';
exports.SET_MOTD_COMPLETE = SET_MOTD_COMPLETE;
var RECEIVE_MESSAGE = 'chat/RECEIVE_MESSAGE';
exports.RECEIVE_MESSAGE = RECEIVE_MESSAGE;
var SEND_MESSAGE = 'chat/SEND_MESSAGE';
exports.SEND_MESSAGE = SEND_MESSAGE;
var NOTIFY = 'chat/NOTIFY';
exports.NOTIFY = NOTIFY;
var LOG = 'chat/LOG';
exports.LOG = LOG;
var REMOVE_MESSAGE = 'chat/REMOVE_MESSAGE';
exports.REMOVE_MESSAGE = REMOVE_MESSAGE;
var REMOVE_USER_MESSAGES = 'chat/REMOVE_USER_MESSAGES';
exports.REMOVE_USER_MESSAGES = REMOVE_USER_MESSAGES;
var REMOVE_ALL_MESSAGES = 'chat/REMOVE_ALL_MESSAGES';
exports.REMOVE_ALL_MESSAGES = REMOVE_ALL_MESSAGES;
var MUTE_USER = 'chat/MUTE_USER';
exports.MUTE_USER = MUTE_USER;
var UNMUTE_USER = 'chat/UNMUTE_USER';
exports.UNMUTE_USER = UNMUTE_USER;
//# sourceMappingURL=chat.js.map
