'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var OPEN_EDIT_MEDIA_DIALOG = exports.OPEN_EDIT_MEDIA_DIALOG = 'dialogs/OPEN_EDIT_MEDIA_DIALOG';
var CLOSE_EDIT_MEDIA_DIALOG = exports.CLOSE_EDIT_MEDIA_DIALOG = 'dialogs/CLOSE_EDIT_MEDIA_DIALOG';

var OPEN_PREVIEW_MEDIA_DIALOG = exports.OPEN_PREVIEW_MEDIA_DIALOG = 'auth/OPEN_PREVIEW_MEDIA_DIALOG';
var CLOSE_PREVIEW_MEDIA_DIALOG = exports.CLOSE_PREVIEW_MEDIA_DIALOG = 'auth/CLOSE_PREVIEW_MEDIA_DIALOG';

var OPEN_LOGIN_DIALOG = exports.OPEN_LOGIN_DIALOG = 'auth/OPEN_LOGIN_DIALOG';
var CLOSE_LOGIN_DIALOG = exports.CLOSE_LOGIN_DIALOG = 'auth/CLOSE_LOGIN_DIALOG';

var OPEN_RESET_PASSWORD_DIALOG = exports.OPEN_RESET_PASSWORD_DIALOG = 'auth/OPEN_RESET_PASSWORD_DIALOG';
var CLOSE_RESET_PASSWORD_DIALOG = exports.CLOSE_RESET_PASSWORD_DIALOG = 'auth/CLOSE_RESET_PASSWORD_DIALOG';
//# sourceMappingURL=dialogs.js.map
//# sourceMappingURL=dialogs.js.map
