"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.HIDE_IMPORT_SOURCE_PANEL = exports.SHOW_IMPORT_SOURCE_PANEL = exports.HIDE_IMPORT_PANEL = exports.SHOW_IMPORT_PANEL = void 0;
var SHOW_IMPORT_PANEL = 'imports/SHOW_IMPORT_PANEL';
exports.SHOW_IMPORT_PANEL = SHOW_IMPORT_PANEL;
var HIDE_IMPORT_PANEL = 'imports/HIDE_IMPORT_PANEL';
exports.HIDE_IMPORT_PANEL = HIDE_IMPORT_PANEL;
var SHOW_IMPORT_SOURCE_PANEL = 'imports/SHOW_IMPORT_SOURCE_PANEL';
exports.SHOW_IMPORT_SOURCE_PANEL = SHOW_IMPORT_SOURCE_PANEL;
var HIDE_IMPORT_SOURCE_PANEL = 'imports/HIDE_IMPORT_SOURCE_PANEL';
exports.HIDE_IMPORT_SOURCE_PANEL = HIDE_IMPORT_SOURCE_PANEL;
//# sourceMappingURL=imports.js.map
