"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.REMOVE_USER_ROLES_COMPLETE = exports.REMOVE_USER_ROLES_START = exports.ADD_USER_ROLES_COMPLETE = exports.ADD_USER_ROLES_START = exports.BAN_USER_COMPLETE = exports.BAN_USER_START = exports.UNMUTE_USER_COMPLETE = exports.UNMUTE_USER_START = exports.MUTE_USER_COMPLETE = exports.MUTE_USER_START = exports.REMOVE_USER_COMPLETE = exports.REMOVE_USER_START = exports.MOVE_USER_COMPLETE = exports.MOVE_USER_START = exports.SKIP_DJ_COMPLETE = exports.SKIP_DJ_START = void 0;
var SKIP_DJ_START = 'moderation/SKIP_DJ_START';
exports.SKIP_DJ_START = SKIP_DJ_START;
var SKIP_DJ_COMPLETE = 'moderation/SKIP_DJ_COMPLETE';
exports.SKIP_DJ_COMPLETE = SKIP_DJ_COMPLETE;
var MOVE_USER_START = 'moderation/MOVE_USER_START';
exports.MOVE_USER_START = MOVE_USER_START;
var MOVE_USER_COMPLETE = 'moderation/MOVE_USER_COMPLETE';
exports.MOVE_USER_COMPLETE = MOVE_USER_COMPLETE;
var REMOVE_USER_START = 'moderation/REMOVE_USER_START';
exports.REMOVE_USER_START = REMOVE_USER_START;
var REMOVE_USER_COMPLETE = 'moderation/REMOVE_USER_COMPLETE';
exports.REMOVE_USER_COMPLETE = REMOVE_USER_COMPLETE;
var MUTE_USER_START = 'moderation/MUTE_USER_START';
exports.MUTE_USER_START = MUTE_USER_START;
var MUTE_USER_COMPLETE = 'moderation/MUTE_USER_COMPLETE';
exports.MUTE_USER_COMPLETE = MUTE_USER_COMPLETE;
var UNMUTE_USER_START = 'moderation/UNMUTE_USER_START';
exports.UNMUTE_USER_START = UNMUTE_USER_START;
var UNMUTE_USER_COMPLETE = 'moderation/UNMUTE_USER_COMPLETE';
exports.UNMUTE_USER_COMPLETE = UNMUTE_USER_COMPLETE;
var BAN_USER_START = 'moderation/BAN_USER_START';
exports.BAN_USER_START = BAN_USER_START;
var BAN_USER_COMPLETE = 'moderation/BAN_USER_COMPLETE';
exports.BAN_USER_COMPLETE = BAN_USER_COMPLETE;
var ADD_USER_ROLES_START = 'moderation/ADD_USER_ROLES_START';
exports.ADD_USER_ROLES_START = ADD_USER_ROLES_START;
var ADD_USER_ROLES_COMPLETE = 'moderation/ADD_USER_ROLES_COMPLETE';
exports.ADD_USER_ROLES_COMPLETE = ADD_USER_ROLES_COMPLETE;
var REMOVE_USER_ROLES_START = 'moderation/REMOVE_USER_ROLES_START';
exports.REMOVE_USER_ROLES_START = REMOVE_USER_ROLES_START;
var REMOVE_USER_ROLES_COMPLETE = 'moderation/REMOVE_USER_ROLES_COMPLETE';
exports.REMOVE_USER_ROLES_COMPLETE = REMOVE_USER_ROLES_COMPLETE;
//# sourceMappingURL=moderation.js.map
