'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var LOAD_PLAYLIST_START = exports.LOAD_PLAYLIST_START = 'playlists/LOAD_PLAYLIST_START';
var LOAD_PLAYLIST_COMPLETE = exports.LOAD_PLAYLIST_COMPLETE = 'playlists/LOAD_PLAYLIST_COMPLETE';
var FILTER_PLAYLIST_ITEMS = exports.FILTER_PLAYLIST_ITEMS = 'playlists/FILTER_PLAYLIST_ITEMS';
var FILTER_PLAYLIST_ITEMS_START = exports.FILTER_PLAYLIST_ITEMS_START = 'playlists/FILTER_PLAYLIST_ITEMS_START';
var FILTER_PLAYLIST_ITEMS_COMPLETE = exports.FILTER_PLAYLIST_ITEMS_COMPLETE = 'playlists/FILTER_PLAYLIST_ITEMS_COMPLETE';
var PLAYLIST_CYCLED = exports.PLAYLIST_CYCLED = 'playlists/PLAYLIST_CYCLED';

var SELECT_PLAYLIST = exports.SELECT_PLAYLIST = 'playlists/SELECT_PLAYLIST';

var ACTIVATE_PLAYLIST_START = exports.ACTIVATE_PLAYLIST_START = 'playlists/ACTIVATE_PLAYLIST_START';
var ACTIVATE_PLAYLIST_COMPLETE = exports.ACTIVATE_PLAYLIST_COMPLETE = 'playlists/ACTIVATE_PLAYLIST_COMPLETE';

var LOAD_ALL_PLAYLISTS_START = exports.LOAD_ALL_PLAYLISTS_START = 'playlists/LOAD_ALL_PLAYLISTS_START';
var LOAD_ALL_PLAYLISTS_COMPLETE = exports.LOAD_ALL_PLAYLISTS_COMPLETE = 'playlists/LOAD_ALL_PLAYLISTS_COMPLETE';

var CREATE_PLAYLIST_START = exports.CREATE_PLAYLIST_START = 'playlists/CREATE_PLAYLIST_START';
var CREATE_PLAYLIST_COMPLETE = exports.CREATE_PLAYLIST_COMPLETE = 'playlists/CREATE_PLAYLIST_COMPLETE';

var RENAME_PLAYLIST_START = exports.RENAME_PLAYLIST_START = 'playlists/RENAME_PLAYLIST_START';
var RENAME_PLAYLIST_COMPLETE = exports.RENAME_PLAYLIST_COMPLETE = 'playlists/RENAME_PLAYLIST_COMPLETE';

var DELETE_PLAYLIST_START = exports.DELETE_PLAYLIST_START = 'playlists/DELETE_PLAYLIST_START';
var DELETE_PLAYLIST_COMPLETE = exports.DELETE_PLAYLIST_COMPLETE = 'playlists/DELETE_PLAYLIST_COMPLETE';

var OPEN_ADD_MEDIA_MENU = exports.OPEN_ADD_MEDIA_MENU = 'playlists/OPEN_ADD_MEDIA_MENU';
var CLOSE_ADD_MEDIA_MENU = exports.CLOSE_ADD_MEDIA_MENU = 'playlists/CLOSE_ADD_MEDIA_MENU';
var ADD_MEDIA_START = exports.ADD_MEDIA_START = 'playlists/ADD_MEDIA_START';
var ADD_MEDIA_COMPLETE = exports.ADD_MEDIA_COMPLETE = 'playlists/ADD_MEDIA_COMPLETE';

var REMOVE_MEDIA_START = exports.REMOVE_MEDIA_START = 'playlists/REMOVE_MEDIA_START';
var REMOVE_MEDIA_COMPLETE = exports.REMOVE_MEDIA_COMPLETE = 'playlists/REMOVE_MEDIA_COMPLETE';

var MOVE_MEDIA_START = exports.MOVE_MEDIA_START = 'playlists/MOVE_MEDIA_START';
var MOVE_MEDIA_COMPLETE = exports.MOVE_MEDIA_COMPLETE = 'playlists/MOVE_MEDIA_COMPLETE';

var UPDATE_MEDIA_START = exports.UPDATE_MEDIA_START = 'playlists/UPDATE_MEDIA_START';
var UPDATE_MEDIA_COMPLETE = exports.UPDATE_MEDIA_COMPLETE = 'playlists/UPDATE_MEDIA_COMPLETE';

var SHUFFLE_PLAYLIST_START = exports.SHUFFLE_PLAYLIST_START = 'playlists/SHUFFLE_PLAYLIST_START';
var SHUFFLE_PLAYLIST_COMPLETE = exports.SHUFFLE_PLAYLIST_COMPLETE = 'playlists/SHUFFLE_PLAYLIST_COMPLETE';
//# sourceMappingURL=playlists.js.map
//# sourceMappingURL=playlists.js.map
