"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DO_CHANGE_USERNAME_COMPLETE = exports.DO_CHANGE_USERNAME_START = exports.RECEIVE_GUEST_COUNT = exports.USER_REMOVE_ROLES = exports.USER_ADD_ROLES = exports.CHANGE_USERNAME = exports.USER_LEAVE = exports.USER_JOIN = exports.LOAD_ONLINE_USERS = void 0;
var LOAD_ONLINE_USERS = 'users/LOAD';
exports.LOAD_ONLINE_USERS = LOAD_ONLINE_USERS;
var USER_JOIN = 'users/JOIN';
exports.USER_JOIN = USER_JOIN;
var USER_LEAVE = 'users/LEAVE';
exports.USER_LEAVE = USER_LEAVE;
var CHANGE_USERNAME = 'users/CHANGE_USERNAME';
exports.CHANGE_USERNAME = CHANGE_USERNAME;
var USER_ADD_ROLES = 'users/ADD_ROLES';
exports.USER_ADD_ROLES = USER_ADD_ROLES;
var USER_REMOVE_ROLES = 'users/REMOVE_ROLES';
exports.USER_REMOVE_ROLES = USER_REMOVE_ROLES;
var RECEIVE_GUEST_COUNT = 'users/RECEIVE_GUEST_COUNT';
exports.RECEIVE_GUEST_COUNT = RECEIVE_GUEST_COUNT;
var DO_CHANGE_USERNAME_START = 'users/DO_CHANGE_USERNAME_START';
exports.DO_CHANGE_USERNAME_START = DO_CHANGE_USERNAME_START;
var DO_CHANGE_USERNAME_COMPLETE = 'users/DO_CHANGE_USERNAME_COMPLETE'; //# sourceMappingURL=users.js.map

exports.DO_CHANGE_USERNAME_COMPLETE = DO_CHANGE_USERNAME_COMPLETE;
//# sourceMappingURL=users.js.map
