"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DO_CLEAR_COMPLETE = exports.DO_CLEAR_START = exports.DO_LOCK_COMPLETE = exports.DO_LOCK_START = exports.DO_LEAVE_COMPLETE = exports.DO_LEAVE_START = exports.DO_JOIN_COMPLETE = exports.DO_JOIN_START = exports.WAITLIST_MOVE = exports.WAITLIST_LEAVE = exports.WAITLIST_JOIN = exports.WAITLIST_UPDATE = exports.WAITLIST_CLEAR = exports.WAITLIST_LOCK = exports.WAITLIST_LOAD = void 0;
var WAITLIST_LOAD = 'waitlist/LOAD';
exports.WAITLIST_LOAD = WAITLIST_LOAD;
var WAITLIST_LOCK = 'waitlist/LOCK';
exports.WAITLIST_LOCK = WAITLIST_LOCK;
var WAITLIST_CLEAR = 'waitlist/CLEAR';
exports.WAITLIST_CLEAR = WAITLIST_CLEAR;
var WAITLIST_UPDATE = 'waitlist/UPDATE';
exports.WAITLIST_UPDATE = WAITLIST_UPDATE;
var WAITLIST_JOIN = 'waitlist/JOIN';
exports.WAITLIST_JOIN = WAITLIST_JOIN;
var WAITLIST_LEAVE = 'waitlist/LEAVE';
exports.WAITLIST_LEAVE = WAITLIST_LEAVE;
var WAITLIST_MOVE = 'waitlist/MOVE';
exports.WAITLIST_MOVE = WAITLIST_MOVE;
var DO_JOIN_START = 'waitlist/DO_JOIN_START';
exports.DO_JOIN_START = DO_JOIN_START;
var DO_JOIN_COMPLETE = 'waitlist/DO_JOIN_COMPLETE';
exports.DO_JOIN_COMPLETE = DO_JOIN_COMPLETE;
var DO_LEAVE_START = 'waitlist/DO_LEAVE_START';
exports.DO_LEAVE_START = DO_LEAVE_START;
var DO_LEAVE_COMPLETE = 'waitlist/DO_LEAVE_COMPLETE';
exports.DO_LEAVE_COMPLETE = DO_LEAVE_COMPLETE;
var DO_LOCK_START = 'waitlist/DO_LOCK_START';
exports.DO_LOCK_START = DO_LOCK_START;
var DO_LOCK_COMPLETE = 'waitlist/DO_LOCK_COMPLETE';
exports.DO_LOCK_COMPLETE = DO_LOCK_COMPLETE;
var DO_CLEAR_START = 'waitlist/DO_CLEAR_START';
exports.DO_CLEAR_START = DO_CLEAR_START;
var DO_CLEAR_COMPLETE = 'waitlist/DO_CLEAR_COMPLETE';
exports.DO_CLEAR_COMPLETE = DO_CLEAR_COMPLETE;
//# sourceMappingURL=waitlist.js.map
