import _jsx from "@babel/runtime/helpers/builtin/jsx";
import React from 'react';
import Uwave from './Uwave';
import youTubeSource from './sources/youtube';
import soundCloudSource from './sources/soundcloud';
var uw = new Uwave({
  apiUrl: 'https://u-wave-demo.now.sh/api',
  socketUrl: 'wss://u-wave-demo.now.sh',
  emoji: {}
}); // Configure the Media sources to be used by this üWave client instance.

uw.source(youTubeSource());
uw.source(soundCloudSource());

var _ref =
/*#__PURE__*/
_jsx(React.Fragment, {}, void 0, _jsx("h2", {}, void 0, "Size report"), _jsx("p", {}, void 0, "Generated by webpack-bundle-analyzer. ", _jsx("a", {
  href: "/report.html",
  target: "_blank"
}, void 0, "View size report")));

uw.setAboutPageComponent(function () {
  return _ref;
});
window.uw = uw;
uw.build().then(function () {
  uw.renderToDOM(document.querySelector('#app'));
  document.querySelector('#app-loading').innerHTML = '';
  document.querySelector('#jss').textContent = '';
}).catch(function (err) {
  document.querySelector('.LoadingScreen-notice').textContent = "Error: " + err.message;
  setTimeout(function () {
    throw err;
  }, 0);
});
//# sourceMappingURL=demo.js.map
