"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.IMPORT_PLAYLIST_COMPLETE = exports.IMPORT_PLAYLIST_START = exports.GET_CHANNEL_PLAYLISTS_COMPLETE = exports.GET_CHANNEL_PLAYLISTS_START = exports.GET_IMPORTABLE_PLAYLIST_COMPLETE = exports.GET_IMPORTABLE_PLAYLIST_START = exports.CHANNEL = exports.PLAYLIST = void 0;
var PLAYLIST = 'youtube/import/PLAYLIST';
exports.PLAYLIST = PLAYLIST;
var CHANNEL = 'youtube/import/CHANNEL';
exports.CHANNEL = CHANNEL;
var GET_IMPORTABLE_PLAYLIST_START = 'youtube/import/GET_IMPORTABLE_PLAYLIST_START';
exports.GET_IMPORTABLE_PLAYLIST_START = GET_IMPORTABLE_PLAYLIST_START;
var GET_IMPORTABLE_PLAYLIST_COMPLETE = 'youtube/import/GET_IMPORTABLE_PLAYLIST_COMPLETE';
exports.GET_IMPORTABLE_PLAYLIST_COMPLETE = GET_IMPORTABLE_PLAYLIST_COMPLETE;
var GET_CHANNEL_PLAYLISTS_START = 'youtube/import/GET_CHANNEL_PLAYLISTS_START';
exports.GET_CHANNEL_PLAYLISTS_START = GET_CHANNEL_PLAYLISTS_START;
var GET_CHANNEL_PLAYLISTS_COMPLETE = 'youtube/import/GET_CHANNEL_PLAYLISTS_COMPLETE';
exports.GET_CHANNEL_PLAYLISTS_COMPLETE = GET_CHANNEL_PLAYLISTS_COMPLETE;
var IMPORT_PLAYLIST_START = 'youtube/import/IMPORT_PLAYLIST_START';
exports.IMPORT_PLAYLIST_START = IMPORT_PLAYLIST_START;
var IMPORT_PLAYLIST_COMPLETE = 'youtube/import/IMPORT_PLAYLIST_COMPLETE';
exports.IMPORT_PLAYLIST_COMPLETE = IMPORT_PLAYLIST_COMPLETE;
//# sourceMappingURL=constants.js.map
