'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PLAYLIST = exports.PLAYLIST = 'youtube/import/PLAYLIST';
var CHANNEL = exports.CHANNEL = 'youtube/import/CHANNEL';

var GET_IMPORTABLE_PLAYLIST_START = exports.GET_IMPORTABLE_PLAYLIST_START = 'youtube/import/GET_IMPORTABLE_PLAYLIST_START';
var GET_IMPORTABLE_PLAYLIST_COMPLETE = exports.GET_IMPORTABLE_PLAYLIST_COMPLETE = 'youtube/import/GET_IMPORTABLE_PLAYLIST_COMPLETE';

var GET_CHANNEL_PLAYLISTS_START = exports.GET_CHANNEL_PLAYLISTS_START = 'youtube/import/GET_CHANNEL_PLAYLISTS_START';
var GET_CHANNEL_PLAYLISTS_COMPLETE = exports.GET_CHANNEL_PLAYLISTS_COMPLETE = 'youtube/import/GET_CHANNEL_PLAYLISTS_COMPLETE';

var IMPORT_PLAYLIST_START = exports.IMPORT_PLAYLIST_START = 'youtube/import/IMPORT_PLAYLIST_START';
var IMPORT_PLAYLIST_COMPLETE = exports.IMPORT_PLAYLIST_COMPLETE = 'youtube/import/IMPORT_PLAYLIST_COMPLETE';
//# sourceMappingURL=constants.js.map
//# sourceMappingURL=constants.js.map
