export var RECEIVE_MOTD = 'chat/RECEIVE_MOTD';
export var SET_MOTD_START = 'chat/SET_MOTD_START';
export var SET_MOTD_COMPLETE = 'chat/SET_MOTD_COMPLETE';
export var RECEIVE_MESSAGE = 'chat/RECEIVE_MESSAGE';
export var SEND_MESSAGE = 'chat/SEND_MESSAGE';
export var NOTIFY = 'chat/NOTIFY';
export var LOG = 'chat/LOG';
export var REMOVE_MESSAGE = 'chat/REMOVE_MESSAGE';
export var REMOVE_USER_MESSAGES = 'chat/REMOVE_USER_MESSAGES';
export var REMOVE_ALL_MESSAGES = 'chat/REMOVE_ALL_MESSAGES';
export var MUTE_USER = 'chat/MUTE_USER';
export var UNMUTE_USER = 'chat/UNMUTE_USER';
//# sourceMappingURL=chat.js.map
