export var OPEN_EDIT_MEDIA_DIALOG = 'dialogs/OPEN_EDIT_MEDIA_DIALOG';
export var CLOSE_EDIT_MEDIA_DIALOG = 'dialogs/CLOSE_EDIT_MEDIA_DIALOG';

export var OPEN_PREVIEW_MEDIA_DIALOG = 'auth/OPEN_PREVIEW_MEDIA_DIALOG';
export var CLOSE_PREVIEW_MEDIA_DIALOG = 'auth/CLOSE_PREVIEW_MEDIA_DIALOG';

export var OPEN_LOGIN_DIALOG = 'auth/OPEN_LOGIN_DIALOG';
export var CLOSE_LOGIN_DIALOG = 'auth/CLOSE_LOGIN_DIALOG';

export var OPEN_RESET_PASSWORD_DIALOG = 'auth/OPEN_RESET_PASSWORD_DIALOG';
export var CLOSE_RESET_PASSWORD_DIALOG = 'auth/CLOSE_RESET_PASSWORD_DIALOG';
//# sourceMappingURL=dialogs.js.map
