export var LOAD_PLAYLIST_START = 'playlists/LOAD_PLAYLIST_START';
export var LOAD_PLAYLIST_COMPLETE = 'playlists/LOAD_PLAYLIST_COMPLETE';
export var FILTER_PLAYLIST_ITEMS = 'playlists/FILTER_PLAYLIST_ITEMS';
export var FILTER_PLAYLIST_ITEMS_START = 'playlists/FILTER_PLAYLIST_ITEMS_START';
export var FILTER_PLAYLIST_ITEMS_COMPLETE = 'playlists/FILTER_PLAYLIST_ITEMS_COMPLETE';
export var PLAYLIST_CYCLED = 'playlists/PLAYLIST_CYCLED';

export var SELECT_PLAYLIST = 'playlists/SELECT_PLAYLIST';

export var ACTIVATE_PLAYLIST_START = 'playlists/ACTIVATE_PLAYLIST_START';
export var ACTIVATE_PLAYLIST_COMPLETE = 'playlists/ACTIVATE_PLAYLIST_COMPLETE';

export var LOAD_ALL_PLAYLISTS_START = 'playlists/LOAD_ALL_PLAYLISTS_START';
export var LOAD_ALL_PLAYLISTS_COMPLETE = 'playlists/LOAD_ALL_PLAYLISTS_COMPLETE';

export var CREATE_PLAYLIST_START = 'playlists/CREATE_PLAYLIST_START';
export var CREATE_PLAYLIST_COMPLETE = 'playlists/CREATE_PLAYLIST_COMPLETE';

export var RENAME_PLAYLIST_START = 'playlists/RENAME_PLAYLIST_START';
export var RENAME_PLAYLIST_COMPLETE = 'playlists/RENAME_PLAYLIST_COMPLETE';

export var DELETE_PLAYLIST_START = 'playlists/DELETE_PLAYLIST_START';
export var DELETE_PLAYLIST_COMPLETE = 'playlists/DELETE_PLAYLIST_COMPLETE';

export var OPEN_ADD_MEDIA_MENU = 'playlists/OPEN_ADD_MEDIA_MENU';
export var CLOSE_ADD_MEDIA_MENU = 'playlists/CLOSE_ADD_MEDIA_MENU';
export var ADD_MEDIA_START = 'playlists/ADD_MEDIA_START';
export var ADD_MEDIA_COMPLETE = 'playlists/ADD_MEDIA_COMPLETE';

export var REMOVE_MEDIA_START = 'playlists/REMOVE_MEDIA_START';
export var REMOVE_MEDIA_COMPLETE = 'playlists/REMOVE_MEDIA_COMPLETE';

export var MOVE_MEDIA_START = 'playlists/MOVE_MEDIA_START';
export var MOVE_MEDIA_COMPLETE = 'playlists/MOVE_MEDIA_COMPLETE';

export var UPDATE_MEDIA_START = 'playlists/UPDATE_MEDIA_START';
export var UPDATE_MEDIA_COMPLETE = 'playlists/UPDATE_MEDIA_COMPLETE';

export var SHUFFLE_PLAYLIST_START = 'playlists/SHUFFLE_PLAYLIST_START';
export var SHUFFLE_PLAYLIST_COMPLETE = 'playlists/SHUFFLE_PLAYLIST_COMPLETE';
//# sourceMappingURL=playlists.js.map
